---
dependencies:
  - "base >=4.8.2.0 && <4.9 || >=4.9.1.0 && <5"
  - "classy-prelude-yesod >=0.10.2 && <1.0 || >=1.1"
  - "yesod >=1.4.3 && <1.5"
  - "yesod-core >=1.4.30 && <1.5"
  - "yesod-auth >=1.4.0 && <1.5"
  - "yesod-static >=1.4.0.3 && <1.6"
  - "yesod-form >=1.4.0 && <1.5"
  - "classy-prelude >=0.10.2"
  - "classy-prelude-conduit >=0.10.2"
  - "bytestring >=0.9 && <0.11"
  - "text >=0.11 && <2.0"
  - "persistent >=2.0 && <2.8"
  - "persistent-mongoDB >= 2.1.2 && < 2.8"
  - mongoDB
  - "persistent-template >=2.0 && <2.8"
  - template-haskell
  - "shakespeare >=2.0 && <2.1"
  - "hjsmin >=0.1 && <0.3"
  - "monad-control >=0.3 && <1.1"
  - "wai-extra >=3.0 && <3.1"
  - "yaml >=0.8 && <0.9"
  - "http-conduit >=2.1 && <2.3"
  - "directory >=1.1 && <1.4"
  - "warp >=3.0 && <3.3"
  - data-default
  - "aeson >=0.6 && <1.3"
  - "conduit >=1.0 && <2.0"
  - "monad-logger >=0.3 && <0.4"
  - "fast-logger >=2.2 && <2.5"
  - "wai-logger >=2.2 && <2.4"
  - file-embed
  - safe
  - unordered-containers
  - containers
  - vector
  - time
  - case-insensitive
  - wai
  - themoviedb
  - "hjsonpointer >= 1.2.0"
executables:
  movie-haskell:
    dependencies:
      - movie-haskell
    ghc-options:
      - "-threaded"
      - "-rtsopts"
      - "-with-rtsopts=-N"
    main: main.hs
    source-dirs: app
    when:
      -
        buildable: false
        condition: flag(library-only)
flags:
  dev:
    default: false
    description: "Turn on development settings, like auto-reload templates."
    manual: false
  library-only:
    default: false
    description: "Build for use with \"yesod devel\""
    manual: false
library:
  source-dirs: src
  when:
    -
      condition: "(flag(dev)) || (flag(library-only))"
      else:
        ghc-options:
          - "-Wall"
          - "-fwarn-tabs"
          - "-O2"
      then:
        cpp-options: "-DDEVELOPMENT"
        ghc-options:
          - "-Wall"
          - "-fwarn-tabs"
          - "-O0"
name: movie-haskell
tests:
  test:
    dependencies:
      - movie-haskell
      - "hspec >=2.0.0"
      - yesod-test
    ghc-options: "-Wall"
    main: Spec.hs
    source-dirs: test
version: "0.0.0"
