---
stanzas:
  -
    args: []
    exec: ../dist/bin/movie-haskell
    hosts:
      - www.movie-haskell.com
    requires-secure: false
    type: webapp
  -
    hosts:
      - static.movie-haskell.com
    root: ../static
    type: static-files
  -
    actions:
      -
        host: www.movie-haskell.com
    hosts:
      - movie-haskell.com
    type: redirect
user-edited: false
