copyright: "Made By <a href=\"http://www.finallybinary.com\">FinallyBinary </a> using Yesod and Haskell"
database:
  connections: 10
  database: movie-haskell
  host: ds161793.mlab.com
  password: movie-haskell-demo
  port: 61793
  user: admin
host: "_env:HOST:*4"
ip-from-header: "_env:IP_FROM_HEADER:false"
port: "_env:PORT:8080"
static-dir: "_env:STATIC_DIR:static"
