




database:
  user:        "movie-haskell"
  password:    "movie-haskell"
  host:        "localhost"
  # See config/test-settings.yml for an override during tests
  database:    "movie-haskell"
  connections: 10
